package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */


public class MyNewJunit {

  private MyNewJunit underTest;


  public void setUp() throws Exception {
  }


  public void addierenTest() {
  }

}
