package de.thb.mps.language.Junit.sandbox;

/*Generated by MPS */


public class TestForJunit5 {

  private TestForJunit5 underTest;


  public void setUp() throws Exception {
  }


  public void addierenTest() {
  }

}
